"""Initial migration.

Revision ID: 45d889d62f48
Revises: 
Create Date: 2023-08-21 16:49:05.763834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '45d889d62f48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_details',
    sa.Column('auth0_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('firstName', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('lastName', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('zipcode', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('phoneNumber', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('dateOfBirth', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('citizenshipStatus', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ssnNumber', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('accountType', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estimatedNetWorth', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('investmentExperience', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hasInvestedBefore', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('investmentReasons', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('investedProjects', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('auth0_id', name='user_details_pkey')
    )
    # ### end Alembic commands ###
